### ISSUE TITLE
Reorganize template structure

### ISSUE THREAD

**Issue by thomaswilburn** [nprapps/dailygraphics-templates#11]
Rather than using the `index.html` and `_content.html` dichotomy, which is a holdover from the old templates, we should explore the idea of an `index.html` that includes `_head.html` and `_foot.html` instead, as this will play better with multi-graphic pages.

**Comment by thomaswilburn** [comment]
Example from the library pandemic graphic: https://github.com/nprapps/graphics-js/blob/master/library-pandemic-20200514/index.html

**Comment by audreycarlsen** [comment]
Closed in commit `fa18292`

**Comment by thomaswilburn** [comment]
Thank you! If you have some time to glance through the README files for DG next and this repo, we should update any place that we used to talk about `_content.html`.
