### ISSUE TITLE
update automated legend for line charts

### ISSUE THREAD

**Issue by DanielJWood** [nprapps/dailygraphics-templates#16]
I've been meaning to do this for a while, but finally implemented it in [a graphic](https://apps.npr.org/dailygraphics/graphics/covid-by-vaccine-status-20211019/preview.html?preview=elderly.html). I dislike the big block for line legends. I still think it's fine for our bar charts. Here's an example:

![image](https://user-images.githubusercontent.com/1298194/138146070-9a837293-4501-4e66-9df0-846d1285051a.png)

@alykat should I go ahead with a PR to implement this change?

**Comment by alykat** [comment]
done in d5300175cf0eace699745507a3fee0bd8aaf854d
