### ISSUE TITLE
New template: Before/after images

### ISSUE THREAD

**Issue by alykat** [nprapps/dailygraphics-templates#19]
Can base off this graphic: https://github.com/nprapps/graphics-js/tree/main/tonga-beforeafter-20220125

Todos:
* Accessibility review (aria labels; should the toggle buttons be radio buttons instead a la the covid trackers)
* Use vanilla JS instead of D3 if possible
* Can this code be generalized so potentially multiple before/afters can be stacked in the same embed?

**Comment by shellyscheng** [comment]
done: https://github.com/nprapps/dailygraphics-templates/pull/36
